spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    schema: classpath:schema.sql
  application:
    name: boai
  jackson:
    time-zone: Asia/Taipei
    date-format: yyyy/MM/dd HH:mm:ss
server:
  servlet:
    context-path: /boai
mybatis:
  mapper-locations: classpath:/sqlmap/*.xml
jwt:
  token-expire-time: 3600000
recaptcha:
  recaptcha-verify-url: https://www.google.com/recaptcha/api/siteverify
  recaptcha-secret: 6Ld6omkqAAAAADMOgoxWdlJj30hJ26JXWhT9bvG6
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  webjars:
    prefix: ""
