spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    schema: classpath:schema.sql
  application:
    name: boai
server:
  servlet:
    context-path: /boai
mybatis:
  mapper-locations: classpath:/sqlmap/*.xml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  webjars:
    prefix: ""
